### ISSUE TITLE
Database accesses must be done out of EDT 

### ISSUE THREAD

**Issue by le-yams** [le-yams/nbmongo#21]
Lot of database accesses related code is executed in EDT. It must be done in background thread with workers.

**Comment by Richard-Cranium** [comment]
Yes, please.  Creating a new index upon a database with a 22 million records will effectively freeze NetBeans for minutes.

**Comment by le-yams** [comment]
Thank you for your feedback, I'll increase this issue priority :-)

Regards,
Yann
