### ISSUE TITLE
Backslashes in values are treated badly and break the DB

### ISSUE THREAD

**Issue by josefsabl** [le-yams/nbmongo#28]
Opening document that has backslashes in one of fields probably badly unescapes these \'s and removes them from the value, effectively breaking the database.

See:

http://screenpresso.com/=sdSIf

**Comment by le-yams** [comment]
Hi josefsabl,
The issue actually comes from the lib I use to prettify the json. I'm making some tests for choosing a new one and I'll publish a new release with this bug fix as soon as I can (probably during the next week ). 

Regards,
Yann

**Comment by josefsabl** [comment]
Cool. Thanks for nice plugin anyway.

**Comment by le-yams** [comment]
Thanks, I'm glad you like it.
I just uploaded a new release with the fix. It should be available through the update center as soon as the validation process is done ;-)

Regards,
Yann

**Comment by josefsabl** [comment]
Thank you!
