### ISSUE TITLE
Create Database Hangs

### ISSUE THREAD

**Issue by daggetlover** [le-yams/nbmongo#45]
After I create a MongoDB connection in the Netbeans Services panel, I then try to create a database. The Create database hangs Netbeans. It appears to be waiting for input for a database name but you cannot enter a name. Any ideas what is wrong?

Thanks.

**Comment by daggetlover** [comment]
Issue was resolved mostly. Needed to have Mongod running. It does hang Netbeans if Mongod is not running.

**Comment by daggetlover** [comment]
Next question; How do I add a Databases driver for the Mongodb connection? It seems when I go to add new driver the Locate Driver finds no driver in the mongodb-java-driver jar.

**Comment by le-yams** [comment]
Hi daggetlover,

Sorry for the late reply, this plugin is indeed a client only and requires a running server (mongod) to connect to.
You don't need to add the mongodb driver (which is provided by this plugin). 
Note that the mongodb driver is NOT a jdbc driver and so you can't connect to a mongodb server using the classic "Database" node which relate to sql databases only (using jdbc).

Best regards,
Yann
