### ISSUE TITLE
It should be possible to open same collection in many tabs

### ISSUE THREAD

**Issue by witoldsz** [le-yams/nbmongo#53]
As of now, when a collection is opened, there is no way to open it again in another tab. It would be very useful to be able to browse a single collection in multiple tabs, so one could work on them with different criteria, projections, etc...

**Comment by le-yams** [comment]
Hi witoldsz,

Actually I added this feature in the last version of the plugin (published only for NetBeans 8.1). I forgot to indicate it in the release note, I'll fix that. 
So right click on the collection node and you'll have a "Open in a new tab" action ;-).

Thanks for your feedback.

Best regards,
Yann
