### ISSUE TITLE
New options: 'add to projection' and 'add to sort'

### ISSUE THREAD

**Issue by witoldsz** [le-yams/nbmongo#55]
It would be useful if one could pick a property of a document and chose one of the two options mentioned in a title. Another version would be not to add, but to replace the projection/sort instead. The decision is to be made :)

**Comment by le-yams** [comment]
Hi witoldsz,

That's indeed a good idea. It could be grouped with the "Find with this property" item which is present in the result tree property nodes popupmenu. That way both policies would be available.

Something like:

* _Query with this property_
  * use as find criteria
  * use as projection
  * _use as sort_
    * ascending
    * descending
  * --
  * add to current criteria
  * add to current projection
  * _add to current sort_
    * ascending
    * descending


Best regards,
Yann

**Comment by witoldsz** [comment]
:+1:  Looks like great idea: very flexible yet easy to use. The only thing I would consider would be not to make extra nesting for sort: *use as sort ascending*, *use as sort descending*. One click less to get there :)
