### ISSUE TITLE
Exception when exporting, cannot reproduce anymore.

### ISSUE THREAD

**Issue by witoldsz** [le-yams/nbmongo#56]
System: Linux version 3.13.0-76-generic running on amd64; UTF-8; en_US (nb)
Java: 1.8.0_45; Java HotSpot(TM) 64-Bit Server VM 25.45-b02
NetBeans: 8.1 (Build 201510222201), 
NBMongo: 8.2.0

I was testing the export feature and it did not really worked. When exporting as a JSON array, the file had only one character: `[` and nothing more. When exporting as document per line, the file was completely blank.

In the IDE log, I have found this:
```
INFO [org.mongodb.driver.connection]: Opened connection [connectionId{localValue:3, serverValue:6}] to mongodb.service.consul:27017
SEVERE [org.openide.util.RequestProcessor]: Error in RequestProcessor org.netbeans.modules.mongodb.util.Exporter
java.lang.NullPointerException
	at org.netbeans.modules.mongodb.util.Exporter.export(Exporter.java:78)
	at org.netbeans.modules.mongodb.util.Exporter.exportTo(Exporter.java:59)
	at org.netbeans.modules.mongodb.util.Exporter.run(Exporter.java:45)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)
```

After rebooting NetBeans, the error did not happen again. Now I cannot reproduce it any longer.

Also, it seems the exception was mishandled somewhere, because it should notify about the problem and not fail silently. Only after opening the (blank) file I noticed something was wrong.

**Comment by witoldsz** [comment]
Today I had it again and again, so I could not export a collection. Same stacktrace, NBMongo 8.2.0.

**Comment by le-yams** [comment]
I have found the cause of this issue, I'll publish a fix before monday ;)
