### ISSUE TITLE
how to change bg color of document list

### ISSUE THREAD

**Issue by gpeach-mdlive** [le-yams/nbmongo#60]
I'm using a dark laf and having trouble with low contrast between bg color and foreground color when opening a collection in a new tab (light grey on white)  is it possible to change this combo and where might I find it in fonts and colors (I've looked)  Great plugin and glad to see this for NB!

**Comment by le-yams** [comment]
Hi gpeach,
If you go in the MongoDB options (__MongoDB__ tab in __Miscellaneous__ options) you can change some rendering font and colors. I don't know if it will fit your needs but don't hesitate to give me any feedback.
Thanks, I'm very glad you like it :)

Best regards,
Yann
