### ISSUE TITLE
Editing a record when using a projection list results in all other fields not part of the projection list being removed from record.

### ISSUE THREAD

**Issue by Richard-Cranium** [le-yams/nbmongo#64]
On the other hand, I don't see how you can fix this when you use mongo's projection function to suppress the display of field information.

It surprised me when it happened.  I can imagine use cases when someone would *want* that behavior, but it's pretty dangerous.  Perhaps a flag that disallows row edits when the projection field isn't empty or a warning when you try?

**Comment by le-yams** [comment]
Hi Richard,

I totally agree with you, this behavior is pretty dangerous. Thanks for pointing that out.

I just think of a third possibility: getting the full document in the editor. 
Even if the query has a projection, it make sense to get the full document on editing/viewing a specific one. 
What do you think about it?

Best regards,
Yann
