### ISSUE TITLE
Edit Query dialog does not support copy paste operations

### ISSUE THREAD

**Issue by darbie** [le-yams/nbmongo#66]

**Comment by le-yams** [comment]
Hi Darbie,

Can you be more specific about your issue ? 
Actually, the query editor is composed of 3 standards JEditorPane that natively support copy/paste operations. Can you provide more details about your issue ?

Regards,
Yann

**Comment by darbie** [comment]
I have netbeans set to use emacs mode.  I have customized some keys.  copy is set to ALT-W. Paste is Ctrl+Y, cut is Ctrl+w.

In nbmongo I can select a database.  I right click on a field like _id and select "copy value".  
I click the "Edit" button.  Then I click on the "Criteria" text area.  Now I can hit Ctrl-Y (yank in emacs) or Ctrl-V (windows paste) and nothing happens for either one.

**Comment by le-yams** [comment]
I set my NetBeans keymap profile to Emacs and the shortcuts you have mentioned are working fine. 
Do you have the problem only in the query editor fields ?

**Comment by darbie** [comment]
yes, only on the query editor fields do I have an issue.

**Comment by le-yams** [comment]
To be honest I don't have any clue about what's causing this issue on your NetBeans :-/ . 
Can you try changing the shortcuts (and/or the keymap profile) and tell me if a configuration makes it work ?
Also could you give me the NetBeans system information (Product Version/Updates/Java/Runtime/System information displayed in the About page) ?

**Comment by darbie** [comment]
I just realized that none of my arrow keys, delete key, etc are working in the query editor.
I am running Netbeans IDE 8.2RC from a few days ago.

Trying the same thing on Netbeans 8.0.2 the problem does not exist.  So it seems to be an issue only on 8.2RC, which you probably don't support yet :)

**Comment by le-yams** [comment]
Indeed, I haven't tested the 8.2RC yet. 
I currently don't have much free time and I am already preparing the next nbmongo version (still for nb8.1/8.0) but I'll try to test it in a few weeks. 
Feel free to get the plugin code from the master and investigate yourself, any help is welcome :)

**Comment by le-yams** [comment]
Hi Darbie,

I finally found what is causing this issue. A "notnull" check is missing when I try to apply the json editorkit on the JEditorPanes in the find criteria component. I'll fix it in a next release.
In the meantime, you can already fix the problem by adding the "HTML5 Kit" plugin in your NetBeans.

Regards,
Yann
